CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	is_admin BOOLEAN DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS subjects(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE,
	title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS threads(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	subject_id TEXT NOT NULL,
	creator_user_id TEXT NOT NULL,
	time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	is_pinned BOOLEAN DEFAULT 0 NOT NULL,
	is_visible BOOLEAN DEFAULT 1 NOT NULL,
	FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
	FOREIGN KEY(creator_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS thread_votes(
	thread_id INTEGER NOT NULL,
	user_id TEXT  NOT NULL,
	PRIMARY KEY (thread_id, user_id),
	FOREIGN KEY(thread_id) REFERENCES threads(id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
